### ISSUE TITLE
关于此博客

### ISSUE THREAD

**Issue by jackeyGao** [jackeyGao/JackeyGao.github.io#70]
https://ijg.io/r/words/about_site.html

**Comment by jackeyGao** [comment]
😯😯😴🥴🤢🤧😷🤐👎🏾

**Comment by sandyzikun** [comment]
竖排诗歌是真的厉害，不知源码在哪里公开？

**Comment by jackeyGao** [comment]
```css
#article .blockquote-valign p {
    line-height: 2 !important;
    text-align: start;
    writing-mode: vertical-rl;
    -moz-writing-mode: vertical-rl;
    -webkit-writing-mode: vertical-rl;
    -o-writing-mode: vertical-rl;
    -ms-writing-mode: tb-rl;
    _writing-mode: tb-rl;
}
```
这个 css 可以控制文本竖排哦。 ：） @sandyzikun
